### PR TITLE
Create skrooge.svg

### PR DESCRIPTION
**Pull request by ChrisP4**
I don't really know how to use github or pull requests. I made an icon for skrooge. Hope this is the correct way to go about adding it. Thanks

### CODE REVIEW

**Comment by gusbemacbe** [comment]
You did it rights. You have already made a PR here. 

But your icons need have to a highlight, a shadow and reflect. Do your icons have?

**Comment by gusbemacbe** [comment]
You have forgotten of making monochromatic icons to the folders 16 and symbolic.

**Comment by ChrisP4** [comment]
Oh, ok thank you. Highlight, shadow and reflect? I'm not sure what these are. Ok, I will make monochromatic icons!

Thank you!!

**Comment by gusbemacbe** [comment]
Hi Chris,

Please visit https://snwh.org/suru/guidelines

Check "Folder Effect", "Shadows", "Highlights" and "Outlines"

**Comment by gusbemacbe** [comment]
Perfect! Please add two icons 16 and symbolic and this same PR will detect, sync and add new files.

**Comment by ChrisP4** [comment]
Erm, I added them but in a new PR. :/ What do I do now?

**Comment by gusbemacbe** [comment]
You did not add monochromatic icons of skrooge to the PR of monochromatic icons of qownnotes. Now you can upload monochromatic icons of skrooge.

**Comment by ChrisP4** [comment]
I am afraid I don't know/understand how I can add icons to the same PR.

**Comment by gusbemacbe** [comment]
Leave the same PR open and you do not need to create each new PR for each icon.

**Comment by gusbemacbe** [comment]
It is! Exactly. You learned how it works!

**Comment by gusbemacbe** [comment]
Ready. Another tip:

Before creating a new PR, put all the files. Then you do not need to create each PR for each file/icon.

**Comment by gusbemacbe** [comment]
Please use the app GitKraken, it is quicker than dragging and dropping on the browser.

**Comment by gusbemacbe** [comment]
Another tip for PR title. When you upload all the files and create one PR, you do not need to write name of all apps in the same title. Write like: "Added new 16 icons" or "Added missed 16 icons", etc. In the description, you can write the names of all apps if you want, and you also can describe the fixes and the improvements.

**Comment by gusbemacbe** [comment]
Can we have your name and your surname? If you do not want to share your real surname, you can give us the fake surname if you want.

**Comment by ChrisP4** [comment]
@gusbemacbe  Chris Escarra

**Comment by gusbemacbe** [comment]
Ready. I uploaded the file [AUTHORS](https://github.com/Magog64/SURU-PLUS/blob/master/AUTHORS).

More another tip:

Since the latest update, our repository is newer than yours, therefore, in your repository you forked, you need to create a new branch for not having conflicts with the newest repository. 

GitKraken offers the option of creating a new branch.

1. Enter in your repository
2. Create a new silly file and put it in your repository.
3. Create a new branch before uploading.
4. Upload. Do not pull request.
5. Delete everything from the new branch.
6. Upload. Do not pull request. 
7. Copy everything from our newest repository.
8. Upload. 
9. Ready, you can put all your new files and pull request.

**Pull request merged**
