### PR TITLE
Create xournal.svg

### PR DESCRIPTION
**Pull request by ChrisP4**
An icon for Xournal I made based on the previous icon

### CODE REVIEW

**Comment by gusbemacbe** [comment]
Hi Chris,

The white shape need to be centred according to Suru Icons Design Guidelines rules. Please check "Unit Grid": https://snwh.org/suru/guidelines

**Comment by gusbemacbe** [comment]
It also needs to have a "folder effect", "highlights", "outlines" and "shadows".

**Comment by gusbemacbe** [comment]
When you intend to make next icons, please study the icons of @Magog64's Suru++. All the icons are in SVG. And also study the icons of my [Suru++ 20](https://github.com/gusbemacbe/suru-plus). 

I prepared two templates, one for Inkscape (for Suru++ Ubuntu) and another for Gravit Designer (for Suru++ 20).

Please avoid:
* blur
* masks (use cut by intersection or vectorise the shapes instead)

[Suru++ Palettes and Templates.tar.gz](https://github.com/Magog64/SURU-PLUS/files/2352809/Suru%2B%2B.Palettes.and.Templates.tar.gz)

**Comment by ChrisP4** [comment]
@gusbemacbe Erm, thanks, I had already created and uploaded these before you texted me on shadows, and the rest. I am in the process of correcting them

**Comment by gusbemacbe** [comment]
If every icon of Suru++ Ubuntu is working without masks bugs on your Kubuntu, then no problems. But anyway, you must contribute for both Suru++ Ubuntu and 20.

**Comment by gusbemacbe** [comment]
If you want to keep using KDE and use Suru++ Ubuntu, just avoid blur and masks, KDE does not support these features. Unfortunately drop shadow, highlights and outlines are also unsupported in KDE, but anyway keep them in both Suru++ Ubuntu and 20.

**Comment by gusbemacbe** [comment]
In spite of merging, your icon still needs a bit improves:

* Remove orange borders
* Add drop shadow to grey shape.

**Comment by ChrisP4** [comment]
What do you mean by: 

> remove orange borders?

For gray shape you mean the block on top right?

**Comment by gusbemacbe** [comment]
Yes

**Pull request merged**
