### PR TITLE
Use this firefox icon until/if the new one takes its place?

### PR DESCRIPTION
**Pull request by ChrisP4**
Do we know that mozilla is definitely going to change firefox's icon to that which looks like gitlab?
At any rate, the previous icon wasn't good in my opinion. But maybe wait until the change has happened?
We could use this icon for a little while?

### CODE REVIEW

**Comment by gusbemacbe** [comment]
It is not what I want. It is what @Magog64 wants. He would like to keep the new Firefox logo.

As your icon improved a lot, it is perfect, but it will be the decision of @Magog64. I will talk with him. 

If he decides to keep his new logo icon, you can put your new icon in my Suru++ 20.

**Comment by gusbemacbe** [comment]
@Magog64 prefers the old icon. You can put your icon in my repository.

I'm going to close this pull request. :-(

**Comment by ChrisP4** [comment]
Lol, why the sad face :). It's ok, I understand. I don't like that icon either. Though I like the new one even less. For my system I have edited elementary's icon for the web browser: https://i.imgur.com/UhrpZMx.png

Also, I used your picture of the colosseum for gwenview. Thanks I will put the icon in your repository._

**Comment by gusbemacbe** [comment]
You are welcome, @ChrisP4

**Pull request merged**
